# Generated by Django 3.1.3 on 2020-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalIncome', models.IntegerField(max_length=10)),
                ('TotalLoss', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PartB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalExpenditure', models.IntegerField(max_length=10)),
                ('TotalBookingScore', models.IntegerField(max_length=10)),
            ],
        ),
    ]
