# Generated by Django 3.1.3 on 2020-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parta',
            name='TotalIncome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parta',
            name='TotalLoss',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partb',
            name='TotalBookingScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partb',
            name='TotalExpenditure',
            field=models.IntegerField(),
        ),
    ]
