# Generated by Django 3.1.3 on 2020-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20201103_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partb',
            fields=[
                ('PartbId', models.AutoField(primary_key=True, serialize=False)),
                ('TotalExpenditure', models.IntegerField()),
                ('BookingScore', models.IntegerField()),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parta',
            name='Year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
